#github.webhook.secret=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
openai.api.key=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
github.app.id=3555495
github.app.private-key-path=file:C:/Users/My Laptop/Downloads/private-key-pkcs8.pem
github.webhook.secret=zeba-arfin